const igracciData = [
{
    id: 1,
    znacka: "Igráček",
    katalogoveCislo: "IGR-01",
    nazev: "Zedník",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1976,
    popis: "Zedník – Úplně první vyrobený Igráček v historii hračkářského podniku. V balení měl bílou ochrannou helmu, zednickou lžíci, lopatu, vědro na maltu a malé červené stavební kolečko.",
    obrazek: "foto_igracci/zednik.jpg",
    doplnky: ["kolečko", "zednická lžíce", "fanka", "lopata", "vědro", "ochranná helma"],
    zajimavost: "První kusy měly specifický hnědý nebo šedý plast nástrojů.",
    specifikace: { profese: "Stavebnictví", rok_vydani: 1976, vybava: "Kolečko, lžíce, kbelík", rarita: "Vysoká (původní)" }
  },
  {
    id: 2,
    znacka: "Igráček",
    katalogoveCislo: "IGR-02",
    nazev: "Kuchař",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1977,
    popis: "Kuchař – Druhá legendární profese v pořadí. Panáček s vysokou tiskařskou čepicí měl k dispozici kompletní maketu kuchyňského pultu, hrnce, váleček na těsto a naběračku.",
    obrazek: "foto_igracci/kuchar.jpg",
    doplnky: ["vysoká kuchařská čepice", "hrnec s poklicí", "naběračka", "váleček", "kuchyňský pult"],
    zajimavost: "Poklice na hrnec je jedním z nejmenších doplňků té doby a velmi snadno se ztrácela.",
    specifikace: { profese: "Gastronomie", rok_vydani: 1977, vybava: "Kuchyňský pult, nádobí", rarita: "Střední" }
  },
  {
    id: 3,
    znacka: "Igráček",
    katalogoveCislo: "IGR-03",
    nazev: "Kominík",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1977,
    popis: "Kominík – Kultovní celočerná postavička s bílou čepicí. Nechyběl mu drátěný strojek na vymetání sazí, ramenní lano a tradiční kominický žebřík.",
    obrazek: "foto_igracci/kominik.jpg",
    doplnky: ["štětka na čištění komínů", "žebřík", "ramenní lano", "bílá čepice"],
    zajimavost: "Jeden z nejžádanějších retro kousků kvůli snadno ztrácející se štětce.",
    specifikace: { profese: "Řemeslo", rok_vydani: 1977, vybava: "Žebřík, štětka, lano", rarita: "Vysoká" }
  },
  {
    id: 4,
    znacka: "Igráček",
    katalogoveCislo: "IGR-04",
    nazev: "Námořník",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1978,
    popis: "Námořník – Přinesl do socialistických dětských pokojů závan dálkových plaveb. Typický modrobílý pruhovaný potisk trupu, námořnická čepice s kšiltem a oranžový záchranný kruh.",
    obrazek: "foto_igracci/namornik.jpg",
    doplnky: ["záchranný kruh", "dalekohled", "kormidlo", "námořnická čepice"],
    zajimavost: "Kormidlo bylo možné upevnit do stojanu, aby samo stálo.",
    specifikace: { profese: "Doprava", rok_vydani: 1978, vybava: "Záchranný kruh, dalekohled", rarita: "Střední" }
  },
  {
    id: 5,
    znacka: "Igráček",
    katalogoveCislo: "IGR-21",
    nazev: "Stavař / Projektant",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1978,
    popis: "Stavař / Projektant – Parťák k zedníkovi. Na rozdíl od něj nosil žlutou helmu a v krabičce měl rýsovací prkno s plány staveb, velký metr a vodováhu.",
    obrazek: "foto_igracci/stavar.jpg",
    doplnky: ["žlutá přilba", "rýsovací pult", "plány stavby", "metr", "vodováha"],
    zajimavost: "Rýsovací pult obsahoval papírovou samolepku s technickým výkresem.",
    specifikace: { profese: "Stavebnictví", rok_vydani: 1978, vybava: "Rýsovací pult, plány", rarita: "Střední" }
  },
  {
    id: 6,
    znacka: "Igráček",
    katalogoveCislo: "IGR-05",
    nazev: "Automechanik",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1979,
    popis: "Automechanik – Velmi populární figurka v modrých montérkách s kšiltovkou. V balení měl pojízdný montážní vozík, sadu klíčů a šroubovák.",
    obrazek: "foto_igracci/automechanik.jpg",
    doplnky: ["montážní vozík", "kufřík na nářadí", "francouzský klíč", "šroubovák", "kšiltovka"],
    zajimavost: "Nářadí z této sady perfektně pasovalo do rukou všem ostatním figurkám z té doby.",
    specifikace: { profese: "Řemeslo", rok_vydani: 1979, vybava: "Montážní vozík, nářadí", rarita: "Střední" }
  },
  {
    id: 7,
    znacka: "Igráček",
    katalogoveCislo: "IGR-06",
    nazev: "Příslušník VB",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1980,
    popis: "Příslušník Veřejné bezpečnosti (VB) – Legendární 'esenbák' v typické uniformě. Nechyběla mu bílá helma s nápisem VB, dopravní terčík a radiostanice.",
    obrazek: "foto_igracci/vb.jpg",
    doplnky: ["bílá helma VB", "bílý opasek", "dopravní terčík", "radiostanice"],
    zajimavost: "Bílá helma věrně kopírovala tehdejší reálný design motocyklových hlídek VB.",
    specifikace: { profese: "Bezpečnost", rok_vydani: 1980, vybava: "Terčík, vysílačka, přilba", rarita: "Vysoká" }
  },
  {
    id: 8,
    znacka: "Igráček",
    katalogoveCislo: "IGR-22",
    nazev: "Cestář",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1980,
    popis: "Cestář – Silniční údržbář v oranžové vestě s lopatou, krumpáčem a nezbytným červenobílým kuželem pro označení práce na silnici.",
    obrazek: "foto_igracci/cestar.jpg",
    doplnky: ["oranžová vesta", "silniční kužel", "lopata", "krumpáč"],
    zajimavost: "Kužel byl vylisován z měkčího ohebného plastu, aby se při hraní nezlomil.",
    specifikace: { profese: "Stavebnictví", rok_vydani: 1980, vybava: "Kužel, lopata, krumpáč", rarita: "Běžná" }
  },
  {
    id: 9,
    znacka: "Igráček",
    katalogoveCislo: "IGR-07",
    nazev: "Doktorka / Zdravotní sestra",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1981,
    popis: "Doktorka / Zdravotní sestra – První ženská postavička v sérii, která měla upravenou sukni. Vybavena lékařským kufříkem, stetoskopem a zkumavkami.",
    obrazek: "foto_igracci/doktorka.jpg",
    doplnky: ["lékařská sukně", "kufřík", "stetoskop", "zkumavky", "pult"],
    zajimavost: "Doplňky měly drobné papírové samolepky s červeným křížem, které se časem rády odlepovaly.",
    specifikace: { profese: "Zdravotnictví", rok_vydani: 1981, vybava: "Kufřík, stetoskop, pult", rarita: "Střední" }
  },
  {
    id: 10,
    znacka: "Igráček",
    katalogoveCislo: "IGR-23",
    nazev: "Horník",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1981,
    popis: "Horník – Havíř s černou helmou a natisknutou čelovou svítilnou. V balení měl sbíječku, krumpáč a dvě makety hnědouhelných briket.",
    obrazek: "foto_igracci/hornik.jpg",
    doplnky: ["hornická helma", "sbíječka", "krumpáč", "makety briket"],
    zajimavost: "Čelová svítilna na helmě byla pouze vylisovaná, nikoli reálně svítící.",
    specifikace: { profese: "Řemeslo", rok_vydani: 1981, vybava: "Sbíječka, krumpáč", rarita: "Vysoká" }
  },
  {
    id: 11,
    znacka: "Igráček",
    katalogoveCislo: "IGR-08",
    nazev: "Požárník / Hasič",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1982,
    popis: "Požárník – Hasič v ochranném obleku s nezbytnou stříbrnou helmu. Balení obsahovalo dlouhou požární hadici, sekeru a proudnici.",
    obrazek: "foto_igracci/pozarnik.jpg",
    doplnky: ["stříbrná přilba", "požární hadice", "sekera", "proudnice"],
    zajimavost: "Tvar přilby přesně odpovídal tehdejším reálným helmám civilní obrany ČSSR.",
    specifikace: { profese: "Záchranáři", rok_vydani: 1982, vybava: "Hadice, sekera, přilba", rarita: "Střední" }
  },
  {
    id: 12,
    znacka: "Igráček",
    katalogoveCislo: "IGR-24",
    nazev: "Řidič důlní lokomotivy",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1982,
    popis: "Řidič důlní lokomotivy – Velmi raritní kousek. Panáček v montérkách s šátkem kolem krku, dodávaný se specifickou malou plastovou mašinkou a důlním vozíkem na uhlí.",
    obrazek: "foto_igracci/duly_ridic.jpg",
    doplnky: ["důlní vozík", "plastová lokomotiva", "šátek", "montérky"],
    zajimavost: "Tento set se vyráběl v menších sériích a dnes patří k nejcennějším kouskům.",
    specifikace: { profese: "Doprava", rok_vydani: 1982, vybava: "Důlní vozík, lokomotiva", rarita: "Extrémní" }
  },
  {
    id: 13,
    znacka: "Igráček",
    katalogoveCislo: "IGR-09",
    nazev: "Zahradník",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1983,
    popis: "Zahradník – Figurka v zelených zahradnických kalhotách s kšiltovkou. Obsahovala plastový záhon s květinami, konve na zalévání, nůžky na živý plot a hrabičky.",
    obrazek: "foto_igracci/zahradnik.jpg",
    doplnky: ["plastový záhon", "květiny", "konev na zalévání", "nůžky na živý plot", "hrabičky"],
    zajimavost: "Květiny se daly ze záhonu jednotlivě vyndávat a " + '"sázet"' + " zpět.",
    specifikace: { profese: "Zemědělství", rok_vydani: 1983, vybava: "Záhon, konve, nářadí", rarita: "Běžná" }
  },
  {
    id: 14,
    znacka: "Igráček",
    katalogoveCislo: "IGR-27",
    nazev: "Motocyklista",
    kategorie: "Vozidla",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1983,
    popis: "Motocyklista – Panáček v kožené kombinéze se specifickou helmou a ochrannými brýlemi. Součástí balení byl velký ohebný plastový motocykl.",
    obrazek: "foto_igracci/motocyklista.jpg",
    doplnky: ["plastový motocykl", "helma", "ochranné brýle", "kombinéza"],
    zajimavost: "Motocykl měl pohyblivá řidítka a kola, dalo se s ním reálně jezdit.",
    specifikace: { profese: "Sport", rok_vydani: 1983, vybava: "Motocykl, helma, brýle", rarita: "Vysoká" }
  },
  {
    id: 15,
    znacka: "Igráček",
    katalogoveCislo: "IGR-10",
    nazev: "Výpravčí / Železničář",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1984,
    popis: "Výpravčí / Železničář – Ikonický panáček v modré železničářské uniformě s červenou čepicí. V balení měl nepostradatelnou výpravku (plácačku), lucernu a jízdní řád.",
    obrazek: "foto_igracci/vypravci.jpg",
    doplnky: ["červená čepice", "výpravka (plácačka)", "lucerna", "jízdní řád"],
    zajimavost: "Jízdní řád byl vyroben z miniaturního kusu potištěného papíru.",
    specifikace: { profese: "Doprava", rok_vydani: 1984, vybava: "Výpravka, čepice, řád", rarita: "Vysoká" }
  },
  {
    id: 16,
    znacka: "Igráček",
    katalogoveCislo: "IGR-25",
    nazev: "Učitelka",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1984,
    popis: "Učitelka – Ženská figurka s brýlemi. Balení obsahovalo školní tabuli s křídami, ukazovátko, učitelský stůl a malé plastové sešity.",
    obrazek: "foto_igracci/ucitelka.jpg",
    doplnky: ["školní tabule", "učitelský stůl", "sešity", "křídy", "ukazovátko", "brýle"],
    zajimavost: "Brýle byly součástí výlisku hlavy, nedaly se panence sundat.",
    specifikace: { profese: "Gastronomie", rok_vydani: 1984, vybava: "Tabule, stůl, sešity", rarita: "Střední" }
  },
  {
    id: 17,
    znacka: "Igráček",
    katalogoveCislo: "IGR-28",
    nazev: "Závodník formule",
    kategorie: "Vozidla",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1984,
    popis: "Závodník formule – Monopost formule v zářivých retro barvách doplněný o řidiče se závodní přilbou a startovním číslem na trupu.",
    obrazek: "foto_igracci/zavodnik_formule.jpg",
    doplnky: ["závodní formule", "přilba", "startovní číslo"],
    zajimavost: "Formule se vyráběly v různých divokých jednobarevných plastech (žlutá, červená, modrá).",
    specifikace: { profese: "Sport", rok_vydani: 1984, vybava: "Závodní formule, helma", rarita: "Vysoká" }
  },
  {
    id: 18,
    znacka: "Igráček",
    katalogoveCislo: "IGR-11",
    nazev: "Hokejista",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1985,
    popis: "Hokejista – Sportovní set reagující na popularitu hokeje v ČSSR. Panáček měl kompletní hokejovou výstroj, helmu s plexisklem, hokejku a puk.",
    obrazek: "foto_igracci/hokejista.jpg",
    doplnky: ["hokejová výstroj", "helma s plexisklem", "hokejku", "puk", "brusle"],
    zajimavost: "Hokejka se často lámala v místě ohybu, najít dnes kompletní set v bezvadném stavu je vzácné.",
    specifikace: { profese: "Sport", rok_vydani: 1985, vybava: "Brusle, hokejka, přilba", rarita: "Střední" }
  },
  {
    id: 19,
    znacka: "Igráček",
    katalogoveCislo: "IGR-26",
    nazev: "Cestovatelka / Turistka",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1985,
    popis: "Cestovatelka / Turistka – Panenka v outdoorovém oblečení, která měla velký kempinkový batoh (krosnu) na záda, mapu a maketu foťáku na krk.",
    obrazek: "foto_igracci/cestovatelka.jpg",
    doplnky: ["kempinkový batoh (krosna)", "mapa", "maketa foťáku"],
    zajimavost: "Krosna držela na zádech pomocí dvou tenkých plastových popruhů, které praskaly.",
    specifikace: { profese: "Sport", rok_vydani: 1985, vybava: "Krosna, foťák, mapa", rarita: "Vysoká" }
  },
  {
    id: 20,
    znacka: "Igráček",
    katalogoveCislo: "IGR-29",
    nazev: "Tříkolka",
    kategorie: "Vozidla",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1985,
    popis: "Tříkolka – Menší doplňkový set určený pro Igráčky-děti. Obsahoval detailně vylisovanou šlapací tříkolku s pohyblivými řidítky.",
    obrazek: "foto_igracci/trikolka.jpg",
    doplnky: ["plastová tříkolka", "pohyblivá řidítka"],
    zajimavost: "Jedná se o jedno z mála čistě dětských příslušenství z 80. let.",
    specifikace: { profese: "Sport", rok_vydani: 1985, vybava: "Plastová tříkolka", rarita: "Střední" }
  },
  {
    id: 21,
    znacka: "Igráček",
    katalogoveCislo: "IGR-12",
    nazev: "Kosmonaut",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1986,
    popis: "Kosmonaut – Vzácný a velmi ceněný set vydaný jako ozvěna letu Vladimíra Remka. Panáček měl bílý skafandr, velkou odklápěcí helmu a maketu průzkumného přístroje.",
    obrazek: "foto_igracci/kosmonaut.jpg",
    doplnky: ["bílý skafandr", "odklápěcí helma", "maketa radaru", "průzkumný přístroj"],
    zajimavost: "Představuje absolutní vrchol sběratelského zájmu z éry ČSSR.",
    specifikace: { profese: "Výzkum", rok_vydani: 1986, vybava: "Skafandr, helma, radar", rarita: "Extrémní" }
  },
  {
    id: 22,
    znacka: "Igráček",
    katalogoveCislo: "IGR-30",
    nazev: "Duna-Buggy",
    kategorie: "Vozidla",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1986,
    popis: "Duna-Buggy – Exoticky vyhlížející plážová bugina z lisovaného barevného plastu s velkými zadními koly a ochranným rámem nad řidičem.",
    obrazek: "foto_igracci/duna_buggy.jpg",
    doplnky: ["terénní vůz Buggy", "ochranný rám", "velká kola"],
    zajimavost: "Design bugin odrážel západní motoristické trendy, které byly v ČSSR tehdy populární.",
    specifikace: { profese: "Sport", rok_vydani: 1986, vybava: "Terénní vůz Buggy", rarita: "Extrémní" }
  },
  {
    id: 23,
    znacka: "Igráček",
    katalogoveCislo: "IGR-13",
    nazev: "Lyžař / Lyžařka",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1987,
    popis: "Lyžař / Lyžařka – Zimní sportovní set. Obsahoval barevné sjezdové lyže s hůlkami, lyžařské brýle a zimní čepici s bambulí.",
    obrazek: "foto_igracci/lyzar.jpg",
    doplnky: ["plastové lyže", "lyžařské hůlky", "lyžařské brýle", "zimní čepice s bambulí"],
    zajimavost: "Lyže se zacvakávaly přímo na hladké spodky bot Igráčka pomocí plastového klipu.",
    specifikace: { profese: "Sport", rok_vydani: 1987, vybava: "Lyže, hůlky, brýle", rarita: "Běžná" }
  },
  {
    id: 24,
    znacka: "Igráček",
    katalogoveCislo: "IGR-14",
    nazev: "Zámečník / Kovář",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1988,
    popis: "Zámečník / Kovář – Řemeslný set s kompletním dílenským ponkem, funkčním malým svěrákem, kovadlinou a sadou kovářského náčiní.",
    obrazek: "foto_igracci/zamecnik.jpg",
    doplnky: ["dílenský ponk", "funkční svěrák", "kovadlina", "kovářské náčiní", "kladivo"],
    zajimavost: "Svěrák měl miniaturní plastový šroub, kterým se dalo reálně otáčet a stahovat čelisti.",
    specifikace: { profese: "Řemeslo", rok_vydani: 1988, vybava: "Ponk, svěrák, kovadlina", rarita: "Střední" }
  },
  {
    id: 25,
    znacka: "Igráček",
    katalogoveCislo: "IGR-31",
    nazev: "Máma a kluk",
    kategorie: "Rodina",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1988,
    popis: "Máma a kluk – Dvoufigurkový rodinný set, který předcházel kočárku. Obsahoval dospělou postavičku ženy a menší postavičku chlapce se školní brašnou.",
    obrazek: "foto_igracci/mama_kluk.jpg",
    doplnky: ["menší figurka chlapce", "školní brašna", "čepice"],
    zajimavost: "Tento set poprvé otestoval výrobu zmenšené figurky dítěte s upraveným trupem.",
    specifikace: { profese: "Rodina", rok_vydani: 1988, vybava: "Školní brašna, čepice", rarita: "Vysoká" }
  },
{
    id: 26,
    znacka: "Igráček",
    katalogoveCislo: "IGR-15",
    nazev: "Voják",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1989,
    popis: "Voják – Příslušník Československé lidové armády (ČSLA) v zelené uniformě. Vybaven vojenskou helmou, polní lahví, dalekohledem a maketou samopalu.",
    obrazek: "foto_igracci/vojak.jpg",
    doplnky: ["vojenská helma", "maketa samopalu", "polní láhev", "dalekohled"],
    zajimavost: "Odstín zeleného plastu přesně odpovídal tehdejší vojenské barvě chaki.",
    specifikace: { profese: "Armáda", rok_vydani: 1989, vybava: "Přilba, samopal, polní láhev", rarita: "Vysoká" }
  },
  {
    id: 27,
    znacka: "Igráček",
    katalogoveCislo: "IGR-16",
    nazev: "Pošťačka",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1989,
    popis: "Pošťačka – Velmi oblíbená ženská figurka v typické uniformě spojů. V balení měla poštovní tašku přes rameno, balíky, dopisy a doručovací razítko.",
    obrazek: "foto_igracci/postacka.jpg",
    doplnky: ["poštovní taška", "plastové balíky", "dopisy", "doručovací razítko"],
    zajimavost: "Balíky a dopisy byly vylisovány jako samostatné kostičky, které šlo vkládat do tašky.",
    specifikace: { profese: "Spoje", rok_vydani: 1989, vybava: "Taška, dopisy, razítko", rarita: "Střední" }
  },
  {
    id: 28,
    znacka: "Igráček",
    katalogoveCislo: "IGR-17",
    nazev: "Matka s dítětem a kočárkem",
    kategorie: "Rodina",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1989,
    popis: "Matka s dítětem a kočárkem – První rodinný set. Obsahoval figurku maminky, funkční hluboký plastový kočárek a miniaturní miminko (které se nedalo ohýbat).",
    obrazek: "foto_igracci/kocarek.jpg",
    doplnky: ["hluboký kočárek", "miniaturní miminko", "peřinka"],
    zajimavost: "Miminko bylo vůbec nejmenším odlitkem v celé historii původní IGRY.",
    specifikace: { profese: "Rodina", rok_vydani: 1989, vybava: "Kočárek, miminko", rarita: "Vysoká" }
  },
  {
    id: 29,
    znacka: "Igráček",
    katalogoveCislo: "IGR-18",
    nazev: "Jezdec s koněm",
    kategorie: "Vozidla",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1990,
    popis: "Jezdec s koněm – Obrovský hit přelomu dekády. Vůbec první set, kde se objevil plnohodnotný ohebný plastový kůň, sedlo, otěže a jezdecký bičík.",
    obrazek: "foto_igracci/jezdec.jpg",
    doplnky: ["plastový kůň", "sedlo", "otěže", "jezdecký bičík"],
    zajimavost: "Kůň měl pohyblivé nohy i hlavu, což byl pro IGRU velký technologický pokrok.",
    specifikace: { profese: "Zvířata", rok_vydani: 1990, vybava: "Kůň, sedlo, bičík", rarita: "Vysoká" }
  },
  {
    id: 30,
    znacka: "Igráček",
    katalogoveCislo: "IGR-19",
    nazev: "Zelinář",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1990,
    popis: "Zelinář – Prodavač v bílé zástěře. Balení obsahovalo prodejní pult, váhu na ovoce, bedýnky a jednotlivé kusy zeleniny vylisované z barevného plastu.",
    obrazek: "foto_igracci/zelinar.jpg",
    doplnky: ["prodejní pult", "váha na ovoce", "bedýnky", "plastová zelenina"],
    zajimavost: "Set obsahoval miniaturní mrkve a hlávky salátu z barevných plastů.",
    specifikace: { profese: "Obchod", rok_vydani: 1990, vybava: "Pult, váha, bedýnky", rarita: "Běžná" }
  },
  {
    id: 31,
    znacka: "Igráček",
    katalogoveCislo: "IGR-20",
    nazev: "Policie",
    kategorie: "Profese",
    era: "Přechodová éra (1991–1994)",
    rokVydani: 1991,
    popis: "Policie – Porevoluční úprava původního esenbáka. Panáček dostal novou tmavě zelenou uniformu s nápisem POLICIE, bílou čepici, pouta a pistoli.",
    obrazek: "foto_igracci/policie.jpg",
    doplnky: ["bílá policejní čepice", "plastová pouta", "pistole"],
    zajimavost: "Forma těla zůstala stejná, změnil se pouze potisk z VB na POLICIE.",
    specifikace: { profese: "Bezpečnost", rok_vydani: 1991, vybava: "Pouta, zbraň, čepice", rarita: "Běžná" }
  },
  {
    id: 32,
    znacka: "Igráček",
    katalogoveCislo: "IGR-32",
    nazev: "Svářeč",
    kategorie: "Profese",
    era: "Přechodová éra (1991–1994)",
    rokVydani: 1992,
    popis: "Svářeč – Těžká dělnická profese přechodové éry. V krabičce se nacházela plně odklápěcí ochranná kukla, hořák a autogenní plynové bomby na pojízdném vozíku.",
    obrazek: "foto_igracci/svarec.jpg",
    doplnky: ["ochranná kukla", "autodílenský hořák", "plynové bomby", "vozík"],
    zajimavost: "Ochrannou kuklu bylo možné mechanicky vyklopit nad hlavu panáčka.",
    specifikace: { profese: "Řemeslo", rok_vydani: 1992, vybava: "Kukla, hořák, bomby", rarita: "Střední" }
  },
  {
    id: 33,
    znacka: "Igráček",
    katalogoveCislo: "IGR-33",
    nazev: "Policista na motorce",
    kategorie: "Vozidla",
    era: "Přechodová éra (1991–1994)",
    rokVydani: 1992,
    popis: "Policista na motorce – Dopravní policie s jednostopým vozidlem. Bílá plastová motorka měla sklopný stojánek a figurka disponovala helmou s otevíracím hledím.",
    obrazek: "foto_igracci/policie_motorka.jpg",
    doplnky: ["bílá motorka", "helma s hledím", "policejní uniforma"],
    zajimavost: "Motorka byla upravenou verzí staršího civilního motocyklu z 80. let.",
    specifikace: { profese: "Bezpečnost", rok_vydani: 1992, vybava: "Motorka, helma", rarita: "Střední" }
  },
  {
    id: 34,
    znacka: "Igráček",
    katalogoveCislo: "IGR-34",
    nazev: "Kadeřnice",
    kategorie: "Profese",
    era: "Přechodová éra (1991–1994)",
    rokVydani: 1993,
    popis: "Kadeřnice – Salónní profese navržená primárně pro dívky. Balení obsahovalo drobný plastový fén na vlasy, hřeben, zrcátko a napodobeniny nůžek.",
    obrazek: "foto_igracci/kadernice.jpg",
    doplnky: ["plastový fén", "hřeben", "zrcátko", "nůžky"],
    zajimavost: "Fén měl drobný výstupek, aby ho panenka dokázala pevně sevřít v ruce.",
    specifikace: { profese: "Služby", rok_vydani: 1993, vybava: "Fén, nůžky, hřeben", rarita: "Běžná" }
  },
  {
    id: 35,
    znacka: "Igráček",
    katalogoveCislo: "IGR-35",
    nazev: "Lyžař (Modernizovaný)",
    kategorie: "Profese",
    era: "Přechodová éra (1991–1994)",
    rokVydani: 1994,
    popis: "Lyžař (Modernizovaný) – Sportovní zimní set s upraveným typem vázání. Barevné plastové lyže a hůlky doplňovala zimní čepice s velkou lisovanou bambulí.",
    obrazek: "foto_igracci/lyzar_94.jpg",
    doplnky: ["plastové lyže", "lyžařské hůlky", "zimní čepice s bambulí"],
    zajimavost: "Oproti verzi z roku 1987 měly lyže mírně odlišný a pevnější plastový úchyt.",
    specifikace: { profese: "Sport", rok_vydani: 1994, vybava: "Lyže, hůlky, čepice", rarita: "Běžná" }
  },
 {
    id: 36,
    znacka: "Igráček",
    katalogoveCislo: "IGR-36",
    nazev: "Cyklista",
    kategorie: "Profese",
    era: "Přechodová éra (1991–1994)",
    rokVydani: 1994,
    popis: "Cyklista – Letní sportovní edice s maketou silničního závodního kola. Nohy Igráčka se volně pokládaly na pevné pedály a set obsahoval i ochrannou helmu.",
    obrazek: "foto_igracci/cyklista.jpg",
    doplnky: ["závodní kolo", "ochranná helma", "sportovní dres"],
    zajimavost: "Kolo mělo integrovaný stojánek vylisovaný přímo na rámu, aby se nepřevracelo.",
    specifikace: { profese: "Sport", rok_vydani: 1994, vybava: "Kolo, cyklo helma", rarita: "Běžná" }
  },
  {
    id: 37,
    znacka: "Igráček",
    katalogoveCislo: "IGR-37",
    nazev: "Rytíř",
    kategorie: "Profese",
    era: "Přelomová éra (1995–1999)",
    rokVydani: 1995,
    popis: "Rytíř – Zásadní technologický milník. Jedná se o vůbec první figurku, která dostala nový typ hlavy s plasticky vystouplým nosem. Vybaven mečem, štítem a brněním.",
    obrazek: "foto_igracci/rytir.jpg",
    doplnky: ["plastový meč", "rytířský štít", "nasazovací brnění", "přilba s hledím"],
    zajimavost: "Do roku 1995 měli všichni Igráčci obličej úplně plochý. Rytíř zavedl novou éru designu.",
    specifikace: { profese: "Dobrodružné", rok_vydani: 1995, vybava: "Meč, štít, brnění", rarita: "Střední" }
  },
  {
    id: 38,
    znacka: "Igráček",
    katalogoveCislo: "IGR-38",
    nazev: "Pirát",
    kategorie: "Profese",
    era: "Přelomová éra (1995–1999)",
    rokVydani: 1996,
    popis: "Pirát – Mořský vlk navazující na úspěch rytíře (rovněž s plastickým nosíkem). Disponoval pirátským šátkem, šavlí, potiskem pásky přes oko a truhlou s mincemi.",
    obrazek: "foto_igracci/pirat.jpg",
    doplnky: ["pirátská šavle", "šátek na hlavu", "truhla s pokladem", "tištěná páska přes oko"],
    zajimavost: "Zlaté mince uvnitř truhly byly součástí jednoho pevného plastového výlisku na dně.",
    specifikace: { profese: "Dobrodružné", rok_vydani: 1996, vybava: "Šavle, šátek, truhla", rarita: "Střední" }
  },
  {
    id: 39,
    znacka: "Igráček",
    katalogoveCislo: "IGR-39",
    nazev: "Truhlář / Tesař",
    kategorie: "Profese",
    era: "Přelomová éra (1995–1999)",
    rokVydani: 1997,
    popis: "Truhlář / Tesař – Tradiční řemeslný set, kde jako hlavní prvek sloužil masivní pracovní ponk, do kterého se dalo ukládat miniaturní nářadí (hoblík, pila, kladivo).",
    obrazek: "foto_igracci/truhlar.jpg",
    doplnky: ["pracovní ponk", "ruční hoblík", "pila", "tesařské kladivo"],
    zajimavost: "Zásuvka v pracovním ponku byla plně výsuvná a funkční.",
    specifikace: { profese: "Řemeslo", rok_vydani: 1997, vybava: "Ponk, hoblík, pila", rarita: "Běžná" }
  },
  {
    id: 40,
    znacka: "Igráček",
    katalogoveCislo: "IGR-40",
    nazev: "Závozník / Řidič",
    kategorie: "Profese",
    era: "Přelomová éra (1995–1999)",
    rokVydani: 1998,
    popis: "Závozník / Řidič – Zásobovací edice vytvořená jako doplněk k populárním velkým plastovým autům Avia. Obsahoval přepravky s vyndavacími lahvemi a transportní rudl.",
    obrazek: "foto_igracci/zavoznik.jpg",
    doplnky: ["přepravní rudl", "plastové přepravky", "miniaturní lahve", "čepice s kšiltem"],
    zajimavost: "Láhve byly vylisované po jednotlivých kusech a daly se z přepravek reálně vyndávat.",
    specifikace: { profese: "Doprava", rok_vydani: 1998, vybava: "Rudl, přepravky, lahve", rarita: "Běžná" }
  },
  {
    id: 41,
    znacka: "Igráček",
    katalogoveCislo: "IGR-41",
    nazev: "Manažer / Podnikatel",
    kategorie: "Profese",
    era: "Finální éra před krachem (2000–2006)",
    rokVydani: 2000,
    popis: "Manažer / Podnikatel – Moderní figurka reagující na přelom milénia. Panáček měl na trupu detailní potisk obleku s kravatou a v ruce držel kufřík a tehdejší mobilní telefon.",
    obrazek: "foto_igracci/manazer.jpg",
    doplnky: ["kufřík na dokumenty", "maketa mobilního telefonu"],
    zajimavost: "Model mobilního telefonu svým tvarem připomínal tehdejší populární robustní telefony.",
    specifikace: { profese: "Služby", rok_vydani: 2000, vybava: "Kufřík, mobilní telefon", rarita: "Nízká" }
  },
  {
    id: 42,
    znacka: "Igráček",
    katalogoveCislo: "IGR-42",
    nazev: "Pracovník technických služeb",
    kategorie: "Profese",
    era: "Finální éra před krachem (2000–2006)",
    rokVydani: 2002,
    popis: "Pracovník technických služeb – Popelář v moderním reflexním oděvu. Hlavním doplňkem byla detailní plastová popelnice s plně otevíracím a zavíracím víkem.",
    obrazek: "foto_igracci/popelar.jpg",
    doplnky: ["plastová popelnice", "uliční koště", "reflexní oděv"],
    zajimavost: "Popelnice svým tvarem přesně odpovídala novým typům městských plastových nádob na odpad.",
    specifikace: { profese: "Služby", rok_vydani: 2002, vybava: "Popelnice, koště", rarita: "Nízká" }
  },
  {
    id: 43,
    znacka: "Igráček",
    katalogoveCislo: "IGR-43",
    nazev: "Skateboardista",
    kategorie: "Profese",
    era: "Finální éra před krachem (2000–2006)",
    rokVydani: 2004,
    popis: "Skateboardista – Úplně poslední nová profese vyvinutá a vydaná původním družstvem IGRA Praha před jeho definitivním ekonomickým krachem v roce 2006.",
    obrazek: "foto_igracci/skateboardista.jpg",
    doplnky: ["plastový skateboard", "kšiltovka otočená dozadu"],
    zajimavost: "Kolečka skateboardu byla pevná a statická, netočila se.",
    specifikace: { profese: "Sport", rok_vydani: 2004, vybava: "Skateboard, kšiltovka", rarita: "Střední" }
  },
{
    id: 44,
    znacka: "Igráček",
    katalogoveCislo: "IGR-12",
    nazev: "Kosmonaut",
    kategorie: "Profese",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1986,
    popis: "Kosmonaut – Absolutní vrchol socialistického hračkářského designu a nejvyhledávanější figurka v celé historii IGRA. Tento exkluzivní set vznikl jako hrdá reakce na vesmírný program Interkosmos a let prvního československého kosmonauta Vladimíra Remka. Panáček disponuje masivním bílým skafandrem s detailními armaturními spoji, velkou aerodynamickou přilbou s plně funkčním odklápěcím průhledným hledím a futuristickým ručním průzkumným radarem.",
    obrazek: "foto_igracci/kosmonaut.jpg",
    doplnky: ["těžký bílý skafandr", "odklápěcí přilba", "průhledné hledí", "vesmírný ruční radar", "přístrojový pult"],
    zajimavost: "Průhledné plexisklo přilby se lisovalo na speciálních strojích a kvůli křehkosti se jich do dnešních dnů dochovalo minimum. Na hrudi měl kosmonaut papírovou samolepku s logem vesmírné mise – uchránit ji před vodou při dětských hrách byl pro tehdejší kluky nadlidský úkol. Dnes má tento božan v kompletním stavu cenu tisíců korun.",
    specifikace: { profese: "Výzkum", rok_vydani: 1986, vybava: "Skafandr, helma, radar", rarita: "Extrémní" }
  },
{
    id: 45,
    znacka: "Igráček",
    katalogoveCislo: "IGR-30",
    nazev: "Duna-Buggy",
    kategorie: "Vozidla",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1986,
    popis: "Duna-Buggy – Neuvěřitelně stylový západní závan, který v roce 1986 totálně ovládl československá pískoviště. Výrobní družstvo IGRA tímto modelem geniálně zareagovalo na tehdejší celosvětovou vlnu popularity plážových bugin. Set obsahoval robustní terénní autíčko z tvrzeného barevného plastu, které se pyšnilo obřími zadními koly s hlubokým drapákovým vzorkem, masivním ochranným rámem proti převrácení a speciálně upraveným řidičem v cool motoristickém úboru.",
    obrazek: "foto_igracci/duna_buggy.jpg",
    doplnky: ["terénní autíčko Buggy", "černý ochranný rám", "široká drapáková kola", "motoristická kšiltovka"],
    zajimavost: "Zatímco většina Igráčků reprezentovala běžná socialistická povolání, Duna-Buggy byla symbolem čisté svobody, dobrodružství a motorismu. Konstrukce kol byla tak odolná, že autíčko zvládalo i ty nejdivočejší sjezdy z písečných dun. Pro sběratele retro hraček je to dnes naprostá designová ikona.",
    specifikace: { profese: "Sport", rok_vydani: 1986, vybava: "Terénní vůz Buggy", rarita: "Extrémní" }
  },
{
    id: 46,
    znacka: "Igráček",
    katalogoveCislo: "IGR-30",
    nazev: "Duna-Buggy",
    kategorie: "Vozidla",
    era: "Klasické retro (1976–1990)",
    rokVydani: 1986,
    popis: "Duna-Buggy – Neuvěřitelně stylový západní závan, který v roce 1986 totálně ovládl československá pískoviště. Výrobní družstvo IGRA tímto modelem geniálně zareagovalo na tehdejší celosvětovou vlnu popularity plážových bugin. Set obsahoval robustní terénní autíčko z tvrzeného barevného plastu, které se pyšnilo obřími zadními koly s hlubokým drapákovým vzorkem, masivním ochranným rámem proti převrácení a speciálně upraveným řidičem v cool motoristickém úboru.",
    obrazek: "foto_igracci/duna_buggy.jpg",
    doplnky: ["terénní autíčko Buggy", "černý ochranný rám", "široká drapáková kola", "motoristická kšiltovka"],
    zajimavost: "Zatímco většina Igráčků reprezentovala běžná socialistická povolání, Duna-Buggy byla symbolem čisté svobody, dobrodružství a motorismu. Konstrukce kol byla tak odolná, že autíčko zvládalo i ty nejdivočejší sjezdy z písečných dun. Pro sběratele retro hraček je to dnes naprostá designová ikona.",
    specifikace: { profese: "Sport", rok_vydani: 1986, vybava: "Terénní vůz Buggy", rarita: "Extrémní" }
  }
];

// Export pro případné použití v modulech
if (typeof module !== 'undefined' && module.exports) {
  module.exports = igracciData;
}